### ISSUE TITLE
Game crashes seconds after world creation 

### ISSUE THREAD

**Issue by diefesson** [Straywave/ImmersiveSnow#20]
# Versions

Minecraft version: 1.20.1
Forge version: 47.3.0

GlitchCore version: 0.0.1.1
Serene Seasons version: 9.1.0.0
ImmersiveSnow version: 1.3.0

# Steps to reproduce

1. Create a instance with only the mods above
2. Create a new world
3. Crash should occur in a few seconds

# Log

full log: https://mclo.gs/vWElY79 

#### Exception
```` java
[22:31:12] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: generateSnowAndIce
	Index: 2
	Listeners:
		0: NORMAL
		1: ASM: class glitchcore.forge.handlers.TickEventHandler onLevelTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		2: ASM: class straywave.minecraft.immersivesnow.forge.EventListener onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
java.lang.NoSuchFieldError: generateSnowAndIce
	at TRANSFORMER/immersivesnow@1.3.0/straywave.minecraft.immersivesnow.forge.hook.SereneSeasonsHook.shouldMelt(SereneSeasonsHook.java:28)
	at TRANSFORMER/immersivesnow@1.3.0/straywave.minecraft.immersivesnow.forge.ModHooksImpl.shouldMelt(ModHooksImpl.java:26)
	at TRANSFORMER/immersivesnow@1.3.0/straywave.minecraft.immersivesnow.ModHooks.shouldMelt(ModHooks.java)
	at TRANSFORMER/immersivesnow@1.3.0/straywave.minecraft.immersivesnow.Logic.shouldMelt(Logic.java:63)
	at TRANSFORMER/immersivesnow@1.3.0/straywave.minecraft.immersivesnow.Logic.checkAndUpdateBlock(Logic.java:52)
	at TRANSFORMER/immersivesnow@1.3.0/straywave.minecraft.immersivesnow.ImmersiveSnowEvents.onWorldTick(ImmersiveSnowEvents.java:51)
	at TRANSFORMER/immersivesnow@1.3.0/straywave.minecraft.immersivesnow.forge.EventListener.onWorldTick(EventListener.java:44)
	at TRANSFORMER/immersivesnow@1.3.0/straywave.minecraft.immersivesnow.forge.__EventListener_onWorldTick_LevelTickEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.3.0/net.minecraftforge.event.ForgeEventFactory.onPostLevelTick(ForgeEventFactory.java:930)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:899)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:840)
````

**Comment by kinnikinnick** [comment]
I'm also getting a crash on start.

**Comment by Straywave** [comment]
Looks like Serene Seasons changed their config structure. It's fixed for newer Minecraft versions, alternatively you can downgrade Serene Seasons to [the last version before the big overhaul](https://modrinth.com/mod/serene-seasons/version/9.0.0.46). (Unless there is some big new feature/fix in Serene Seasons that was released, I don't see any reason to backport?)
